<a href="https://colab.research.google.com/github/deductiveclouds/Pytorch/blob/main/%5BGK%5D_00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
torch.__version__

'2.5.1+cu124'

In [ ]:
scalar = torch.tensor(11)
scalar

tensor(11)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

11

In [ ]:
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
from re import M
MATRIX = torch.tensor([[1,2], [3, 4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.6541, 0.4807, 0.2162, 0.6168],
         [0.4428, 0.6608, 0.6194, 0.8620],
         [0.2795, 0.6055, 0.4958, 0.5483]]),
 torch.float32)

In [ ]:
random_image_tensor = torch.rand(size=[224, 224, 3])
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
zeros = torch.zeros([2,5])
zeros, zeros.dtype

(tensor([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]),
 torch.float32)

In [ ]:
ones = torch.ones(size=[4,3])
ones, ones.dtype

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 torch.float32)

In [33]:
torch.arange(1, 10, 2)

tensor([1, 3, 5, 7, 9])

In [35]:
torch.ones_like(torch.arange(1, 6))

tensor([1, 1, 1, 1, 1])

In [36]:
torch.tensor([1]).device

device(type='cpu')

In [38]:
torch.tensor([1], dtype=torch.float64)

tensor([1.], dtype=torch.float64)

In [40]:
torch.tensor([1, 2, 3]) / 3

tensor([0.3333, 0.6667, 1.0000])

In [42]:
torch.div(torch.tensor([1, 2, 3]), 3, rounding_mode='floor')

tensor([0, 0, 1])

In [43]:
x = torch.tensor([1, 2, 3])
x * x

tensor([1, 4, 9])

In [44]:
x = torch.tensor([[1, 2], [3, 4]])
x * x, torch.matmul(x, x)

(tensor([[ 1,  4],
         [ 9, 16]]),
 tensor([[ 7, 10],
         [15, 22]]))

In [48]:
torch.nn.Linear(2, 6)(torch.tensor([1.0, 2.0]))

tensor([-1.4287,  0.6145, -1.3357,  0.9873,  1.3536, -0.7536],
       grad_fn=<ViewBackward0>)

In [49]:
torch.mean(torch.tensor([1.0, 2.0, 3.0]))

tensor(2.)

In [52]:
torch.argmax(torch.tensor([1, 2, 3, 4, 8, 6]))

tensor(4)

In [53]:
x = torch.tensor([1])
x.dtype

torch.int64

In [55]:
x.type(torch.float16)

tensor([1.], dtype=torch.float16)

In [60]:
x = torch.tensor([1, 2])
y = x.view(2, 1)
y[0][0] = 8
x

tensor([8, 2])

In [63]:
torch.stack([x, x, x], dim=0), torch.stack([x, x, x], dim=1)

(tensor([[8, 2],
         [8, 2],
         [8, 2]]),
 tensor([[8, 8, 8],
         [2, 2, 2]]))

In [67]:
x = torch.tensor([[1, 2]])
y = torch.squeeze(x)
y, torch.unsqueeze(y, dim=0)

(tensor([1, 2]), tensor([[1, 2]]))

In [71]:
x = torch.rand((2, 2, 2))
x, x.permute(2, 1, 0)

(tensor([[[0.0644, 0.3911],
          [0.5972, 0.8061]],
 
         [[0.8875, 0.1828],
          [0.4395, 0.5694]]]),
 tensor([[[0.0644, 0.8875],
          [0.5972, 0.4395]],
 
         [[0.3911, 0.1828],
          [0.8061, 0.5694]]]))

In [77]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [102]:
# To get only 5, 8 from the above.
x[:, :, 1].squeeze()[1:]

tensor([5, 8])

###...here...

In [107]:
import torch
import numpy as np

x = torch.from_numpy(np.arange(1., 11.))
x, x.dtype, x.device

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64),
 torch.float64,
 device(type='cpu'))

In [109]:
x.numpy()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [117]:
torch.manual_seed(42)

torch.rand(2, 3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [119]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [121]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [123]:
torch.cuda.device_count()

0

In [125]:
import torch

torch.backends.mps.is_available()

False

In [126]:
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

'cpu'

In [127]:
if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"
else:
    device = "cpu"